### ISSUE TITLE
Compatibility wtih 5 prime only adapter?

### ISSUE THREAD

**Issue by cnk113** [phipsonlab/NextClone#4]
So for my clonal barcode dataset we generally only have a 5 prime sequence since are barcode is long and we do separate amplification the barcode library (and cycle only to the barcode length as a result). Is there a way to just set only a 5 prime adapter and take those inserts?
It looks like flexiplex allows that but I wondered if your interface/call will allow it.

Best,
Chang

**Comment by ghar1821** [comment]
yes you can do that. All you need to do is leave the `adapter_3prime_clonmapper` parameter in `nextclone.config` file as empty string like so: `adapter_3prime_clonmapper = ""`
